# -*- coding: utf-8 -*-
"""ejercicio3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YoJIc1fE4QPTXxflCDMhdjm7rsuBX1rD
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Ejercicio 3

## 1. Cree un archivo llamado elecciones.json
"""

import pandas as pd
import json
votantes=[
  {
    "Departamento": "Antioquia",
    "Cantidad_Votantes_Hombres": 1250000,
    "Cantidad_Votantes_Mujeres": 1300000
  },
  {
    "Departamento": "Cundinamarca",
    "Cantidad_Votantes_Hombres": 980000,
    "Cantidad_Votantes_Mujeres": 1020000
  },
  {
    "Departamento": "Valle del Cauca",
    "Cantidad_Votantes_Hombres": 900000,
    "Cantidad_Votantes_Mujeres": 950000
  },
  {
    "Departamento": "Atlántico",
    "Cantidad_Votantes_Hombres": 620000,
    "Cantidad_Votantes_Mujeres": 650000
  },
  {
    "Departamento": "Santander",
    "Cantidad_Votantes_Hombres": 540000,
    "Cantidad_Votantes_Mujeres": 560000
  },
  {
    "Departamento": "Bolívar",
    "Cantidad_Votantes_Hombres": 500000,
    "Cantidad_Votantes_Mujeres": 520000
  },
  {
    "Departamento": "Boyacá",
    "Cantidad_Votantes_Hombres": 410000,
    "Cantidad_Votantes_Mujeres": 430000
  },
  {
    "Departamento": "Nariño",
    "Cantidad_Votantes_Hombres": 380000,
    "Cantidad_Votantes_Mujeres": 400000
  },
  {
    "Departamento": "Tolima",
    "Cantidad_Votantes_Hombres": 360000,
    "Cantidad_Votantes_Mujeres": 370000
  },
  {
    "Departamento": "Meta",
    "Cantidad_Votantes_Hombres": 220000,
    "Cantidad_Votantes_Mujeres": 230000
  }
]
with open("/content/drive/MyDrive/Examen python/datasets/elecciones.json", "w", encoding="utf-8") as archivo:
  json.dump(votantes, archivo,  indent=4 , ensure_ascii=False)

"""### 3. Generar un archivo nuevo denominado mayoria_mujeres_departamento.json con los departamentos donde la cantidad de votantes mujeres fue mayor a la de los hombres"""

df=pd.read_json("/content/drive/MyDrive/Examen python/datasets/elecciones.json")
df
Total_votantes=df["Cantidad_Votantes_Hombres"]+df["Cantidad_Votantes_Mujeres"]
df["Total_votantes"]=Total_votantes
porcentaje_Hombres=df["Cantidad_Votantes_Hombres"]/df["Total_votantes"]
porcentaje_Mujeres=df["Cantidad_Votantes_Mujeres"]/df["Total_votantes"]
df["porcentaje_Hombres"]=porcentaje_Hombres
df["porcentaje_Mujeres"]=porcentaje_Mujeres
print(df)
df.to_json("/content/drive/MyDrive/Examen python/datasets/mayoria_mujeres_departamento.json",indent=4,force_ascii=False,orient="records")