# -*- coding: utf-8 -*-
"""ejercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0N4e_Y323e8q6mzRzt3bmr8PgbBmilI

# 1. Cree un archivo llamado inventario.csv
"""



from google.colab import drive
drive.mount('/content/drive')

import csv


datos=[
    ["codigo","nombre","precio","cantidad"],
    ["p001","Arroz 1KG",4500,50],
    ["p002","Leche entera",3200,35],
    ["p003","Pan Tajado",3800,20],
    ["p004","Aceite Vegetal",9500,15],
    ["p005","Huevos Docena",10200,25]
]
with open("/content/drive/MyDrive/Examen python/datasets/inventario.csv", "w", newline="", encoding="utf-8") as archivo:
    escritor=csv.writer(archivo)
    escritor.writerows(datos)

"""# 3.Leer archivo csv y mostrar todos los registros

"""

import csv

with open("/content/drive/MyDrive/Examen python/datasets/inventario.csv", "r", encoding="utf-8") as archivo:
    lector=csv.reader(archivo)
    for fila in lector:
        print(fila)

"""# 4. Mostrar valor total inventario"""

valorTotalInventario = 0

for producto in datos[1:]:
    precio = producto[2]
    cantidad = producto[3]
    valorProducto=precio*cantidad
    valorTotalInventario += precio * cantidad
    print("Valor total del producto: ", producto[1], " = ", valorProducto)
print("Valor total del inventario es: ",valorTotalInventario)

