# -*- coding: utf-8 -*-
"""ejercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOuYdyn-VBANL9VBxfthslbjqelYGAFN
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Ejercicio 4

### 1. Leer archivo json con información de deportistas colombianos desde la siguiente url https://raw.githubusercontent.com/CesarMCuellarCha/archivosCSV/refs/heads/main/deportistas.json
"""

import pandas as pd
import json

df= pd.read_json("https://raw.githubusercontent.com/CesarMCuellarCha/archivosCSV/refs/heads/main/deportistas.json")
df

"""### 2. Hacer un filtro de deportista de genero femenino y exportarlo a un archivo nuevo llamado deportistas_mujeres.json"""

deportistas_mujeres = df[df['sexo']=="Femenino"]
print(deportistas_mujeres)
deportistas_mujeres.to_json("/content/drive/MyDrive/Examen python/datasets/deportistas_mujeres.json",indent=4,orient="records",force_ascii=False)

"""### 3. Hacer un filtro de deportistas cuyo deporte es ciclismo de ruta y cuya edad este entre 28 y 35 años. Exportar los resultados en un archivo llamado deportistas_ciclismo_ruta.json"""

df= pd.read_json("https://raw.githubusercontent.com/CesarMCuellarCha/archivosCSV/refs/heads/main/deportistas.json")
df
deportistas_ciclismo_ruta = df[(df['deporte']=="Ciclismo de ruta") & (df['edad']>=28) & (df['edad']<=35)]
print(deportistas_ciclismo_ruta)
deportistas_ciclismo_ruta.to_json("/content/drive/MyDrive/Examen python/datasets/deportistas_ciclismo_ruta.json",indent=4,orient="records",force_ascii=False)

"""### 4. Calcular promedio de edad de las mujeres cuyo deporte es baloncesto"""

df=pd.read_json("https://raw.githubusercontent.com/CesarMCuellarCha/archivosCSV/refs/heads/main/deportistas.json")
MujeresBaloncesto = df[(df['sexo']=="Femenino") & (df['deporte']=="Baloncesto")]
promedioMujeresBaloncesto = MujeresBaloncesto['edad'].mean()
print(promedioMujeresBaloncesto)

"""### 5. Mostrar los datos del deportista de mayor de edad y cuyo sexo sea Masculino"""

df=pd.read_json("https://raw.githubusercontent.com/CesarMCuellarCha/archivosCSV/refs/heads/main/deportistas.json")
deportistaMayorEdad= df[(df['sexo']=="Masculino") & (df['edad']>18)]
print(deportistaMayorEdad)

"""### Generar un archivo nuevo con los deportistas cuya estatura supere los 1.85 con el nombre deportistas_estatura_mayor_1.85.json"""

df=pd.read_json("https://raw.githubusercontent.com/CesarMCuellarCha/archivosCSV/refs/heads/main/deportistas.json")
df
deportistaMas185 =df[df['estatura']>1.85]
print(deportistaMas185)
deportistaMas185.to_json("/content/drive/MyDrive/Examen python/datasets/deportistas_estatura_mayor_1.85.json",indent=4,orient="records",force_ascii=False)