# -*- coding: utf-8 -*-
"""Ejercicio2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSMEtg1_ov3cZ6XWKnnjoPihrwfyXKnq
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Ejercicio 2

# 1. Lea el archivo usando pandas
"""

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Examen python/datasets/inventario.csv")
print(df)

"""# 2. Mostrar

# 2.1 Producto mas costoso
"""

masCaro=df[df["precio"]==df["precio"].max()]
print("El producto mas caro es: ",masCaro)

"""# 2.2 Producto con mayor cantidad"""

masCantidad=df[df["cantidad"]==df["cantidad"].max()]
print("El producto con mayor cantidad es: ",masCantidad)

"""# 3. Cree una nueva columna llamda valor_total calculada de la siguiente forma:
      valor_total=precio*cantidad
"""

df["valor_total"] = df['cantidad'] * df['precio']
print(df)

df.to_csv("/content/drive/MyDrive/Examen python/datasets/inventario_actualizado.csv", index=False)